export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES'; //home
export const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME';
export const GET_VIDEOGAME_BY_ID = 'GET_VIDEOGAME_BY_ID'; 
export const GET_GENRES = 'GET_GENRES';
export const ORDER_ALPHABETICALLY = 'ORDER_ALPHABETICALLY'; // ORDEN ALFABETICO
export const ORDER_BY_GENRES = 'ORDER_BY_GENRES';
export const ORDER_BY_RAITING = 'ORDER_BY_RAITING'; //MAS POPULARES
export const CREATED_GAMES = 'CREATED_GAMES'; // JUEGOS DE LA DB
export const CREATE_GAME = 'CREATE_GAME' // POST - FORMULARIO
export const MODIFY_GAME = 'MODIFY_GAME'; //PUT - FORMULARIO 
export const DELETED_GAME = 'DELETED_GAME';

