export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES'; //home
export const GET_VIDEOGAMES_BY_ORIGIN = 'GET_VIDEOGAMES_BY_ORIGIN'; //JUEGOS DE LA DB
export const GET_VIDEOGAMES_BY_NAME = 'GET_VIDEOGAMES_BY_NAME'; //BUSCA POR NOMBRE DE VIDEOGAME
export const GET_VIDEOGAME_BY_ID = 'GET_VIDEOGAME_BY_ID';
export const GET_GENRES = 'GET_GENRES';
export const ORDER_ALPHABETICALLY = 'ORDER_ALPHABETICALLY'; // ORDEN ALFABETICO
export const FILTER_BY_GENRES = 'FILTER_BY_GENRES';
export const ORDER_BY_RAITING = 'ORDER_BY_RAITING'; //MAS POPULARES
export const CREATED_GAMES = 'CREATED_GAMES'; // JUEGOS DE LA DB
export const CREATE_GAME = 'CREATE_GAME' // POST - FORMULARIO
export const MODIFY_GAME = 'MODIFY_GAME'; //PUT - FORMULARIO 
export const DELETED_GAME = 'DELETED_GAME';
export const DELETE_STATES = 'DELETE_STATES'

